(() => {
  const songs=(window.SONGS||[]).map((song,index)=>({...song,id:index}));
  const els={search:document.querySelector("#songSearch"),suggestions:document.querySelector("#suggestions"),guess:document.querySelector("#guessButton"),rows:document.querySelector("#guessRows"),status:document.querySelector("#guessStatus"),message:document.querySelector("#message"),daily:document.querySelector("#dailyMode"),practice:document.querySelector("#practiceMode"),resetPuzzle:document.querySelector("#resetPuzzleButton"),playAnother:document.querySelector("#playAnotherButton"),completion:document.querySelector("#completionPanel"),completionMark:document.querySelector("#completionMark"),answerBox:document.querySelector("#answerBox"),completionSummary:document.querySelector("#completionSummary"),modeTitle:document.querySelector("#modeTitle"),roundLabel:document.querySelector("#roundLabel")};
  const MAX_GUESSES=6;
  const CATALOG_VERSION=2;
  const normalize=value=>String(value||"").toLowerCase().normalize("NFKD").replace(/[^a-z0-9]+/g," ").trim();
  let mode="daily",target=null,selected=null,guesses=[],finished=false,activeSuggestion=-1;
  function dateKey(){const d=new Date();return[d.getFullYear(),String(d.getMonth()+1).padStart(2,"0"),String(d.getDate()).padStart(2,"0")].join("-")}
  function hash(str){let value=2166136261;for(const char of str){value^=char.charCodeAt(0);value=Math.imul(value,16777619)}return value>>>0}
  function dailyTarget(){return songs[hash(dateKey())%songs.length]}
  function randomTarget(previous){if(songs.length<2)return songs[0];let next;do{next=songs[Math.floor(Math.random()*songs.length)]}while(previous&&next.id===previous.id);return next}
  function dailyStorageKey(){return"drainle-daily-v"+CATALOG_VERSION+"-"+dateKey()}
  function loadDaily(){try{const saved=JSON.parse(localStorage.getItem(dailyStorageKey())||"null");if(saved&&Array.isArray(saved.guesses)){guesses=saved.guesses.map(id=>songs[id]).filter(Boolean);finished=Boolean(saved.finished)}}catch{}}
  function saveDaily(){if(mode==="daily")localStorage.setItem(dailyStorageKey(),JSON.stringify({guesses:guesses.map(s=>s.id),finished}))}
  function readStats(){try{return JSON.parse(localStorage.getItem("drainle-stats")||'{"played":0,"wins":0,"streak":0}')}catch{return{played:0,wins:0,streak:0}}}
  function writeStats(won){const stats=readStats();stats.played+=1;if(won){stats.wins+=1;stats.streak+=1}else stats.streak=0;localStorage.setItem("drainle-stats",JSON.stringify(stats));updateStats()}
  function updateStats(){const s=readStats();document.querySelector("#playedStat").textContent=s.played;document.querySelector("#winsStat").textContent=s.wins;document.querySelector("#streakStat").textContent=s.streak}
  function setMode(nextMode){mode=nextMode;selected=null;els.search.value="";els.suggestions.hidden=true;els.daily.classList.toggle("active",mode==="daily");els.practice.classList.toggle("active",mode==="practice");els.daily.setAttribute("aria-selected",String(mode==="daily"));els.practice.setAttribute("aria-selected",String(mode==="practice"));if(mode==="daily"){target=dailyTarget();guesses=[];finished=false;loadDaily();els.modeTitle.textContent="daily song";els.roundLabel.textContent="resets at midnight";els.resetPuzzle.hidden=true}else{target=randomTarget(target);guesses=[];finished=false;els.modeTitle.textContent="practice mode";els.roundLabel.textContent="unlimited rounds";els.resetPuzzle.hidden=false}els.message.textContent="";render()}
  function newPracticeSong(){target=randomTarget(target);guesses=[];finished=false;selected=null;els.search.value="";els.message.textContent="new puzzle ready";render();els.search.focus()}
  function matches(query,song){const q=normalize(query);return q&&(normalize(song.title).includes(q)||normalize(song.artist).includes(q)||normalize(song.album).includes(q))}
  function showSuggestions(){const query=els.search.value;selected=null;els.guess.disabled=true;activeSuggestion=-1;if(!normalize(query)){els.suggestions.hidden=true;return}const found=songs.filter(song=>matches(query,song)&&!guesses.some(g=>g.id===song.id)).slice(0,10);els.suggestions.innerHTML="";for(const song of found){const button=document.createElement("button");button.className="suggestion";button.type="button";button.setAttribute("role","option");button.innerHTML="<strong></strong><span></span>";button.querySelector("strong").textContent=song.title;button.querySelector("span").textContent=[song.artist,song.album,song.year].filter(Boolean).join(" · ");button.addEventListener("click",()=>selectSong(song));els.suggestions.appendChild(button)}els.suggestions.hidden=found.length===0}
  function selectSong(song){selected=song;els.search.value=song.title;els.suggestions.hidden=true;els.guess.disabled=finished;els.guess.focus()}
  function categoricalClass(guess,answer){return normalize(guess)===normalize(answer)?"feedback-exact":"feedback-far"}
  function numericFeedback(guess,answer,closeRange){const delta=Math.abs(Number(guess)-Number(answer));return{className:delta===0?"feedback-exact":delta<=closeRange?"feedback-close":"feedback-far",arrow:delta===0?"":Number(guess)<Number(answer)?"↑":"↓"}}
  function makeCell(value,label,className="",arrow=""){const cell=document.createElement("div");cell.className="cell "+className;cell.dataset.label=label;const text=document.createElement("span");text.textContent=value||"none";cell.appendChild(text);if(arrow){const a=document.createElement("span");a.className="arrow";a.textContent=arrow;cell.appendChild(a)}return cell}
  function renderRow(song,index){const row=document.createElement("div");row.className="guess-grid guess-row";if(song.id===target.id)row.classList.add("is-correct");row.style.animationDelay=String(index*45)+"ms";const year=numericFeedback(song.year,target.year,2);const track=numericFeedback(song.track,target.track,2);row.append(makeCell(song.title,"song"),makeCell(song.artist,"artist",categoricalClass(song.artist,target.artist)),makeCell(song.features||"none","features",categoricalClass(song.features,target.features)),makeCell(song.album,"album",categoricalClass(song.album,target.album)),makeCell(song.year,"year",year.className,year.arrow),makeCell(song.track,"track #",track.className,track.arrow));return row}
  function render(){els.rows.innerHTML="";guesses.forEach((song,index)=>els.rows.appendChild(renderRow(song,index)));const remaining=Math.max(0,MAX_GUESSES-guesses.length);els.status.textContent=mode==="daily"?remaining+" guess"+(remaining===1?"":"es")+" remaining":guesses.length+" guess"+(guesses.length===1?"":"es")+" · unlimited";els.search.disabled=finished;els.guess.disabled=finished||!selected;const wasHidden=els.completion.hidden;els.completion.hidden=!finished;els.playAnother.hidden=mode!=="practice";els.completion.classList.remove("is-loss");if(finished){const won=guesses.at(-1)?.id===target.id;els.message.textContent="";els.completionMark.textContent=won?"correct ✓":"puzzle complete";els.answerBox.textContent=target.title+" by "+target.artist;els.completionSummary.textContent=won?"solved in "+guesses.length+" "+(guesses.length===1?"try":"tries"):"not solved in "+guesses.length+" tries";if(!won)els.completion.classList.add("is-loss");if(wasHidden)requestAnimationFrame(()=>els.completion.scrollIntoView({behavior:"smooth",block:"center"}))}}
  function submitGuess(){if(!selected||finished)return;guesses.push(selected);const won=selected.id===target.id;selected=null;els.search.value="";els.guess.disabled=true;if(won||(mode==="daily"&&guesses.length>=MAX_GUESSES)){finished=true;writeStats(won)}saveDaily();render();els.search.focus()}
  function moveSuggestion(direction){const items=[...els.suggestions.querySelectorAll(".suggestion")];if(!items.length)return;activeSuggestion=(activeSuggestion+direction+items.length)%items.length;items.forEach((item,i)=>item.classList.toggle("active",i===activeSuggestion));items[activeSuggestion].scrollIntoView({block:"nearest"})}
  els.search.addEventListener("input",showSuggestions);els.search.addEventListener("keydown",event=>{if(event.key==="ArrowDown"){event.preventDefault();moveSuggestion(1)}if(event.key==="ArrowUp"){event.preventDefault();moveSuggestion(-1)}if(event.key==="Enter"){event.preventDefault();const items=[...els.suggestions.querySelectorAll(".suggestion")];if(!els.suggestions.hidden&&activeSuggestion>=0)items[activeSuggestion].click();else if(selected)submitGuess()}if(event.key==="Escape")els.suggestions.hidden=true});
  document.addEventListener("click",event=>{if(!event.target.closest(".search-wrap"))els.suggestions.hidden=true});els.guess.addEventListener("click",submitGuess);els.daily.addEventListener("click",()=>setMode("daily"));els.practice.addEventListener("click",()=>setMode("practice"));els.resetPuzzle.addEventListener("click",newPracticeSong);els.playAnother.addEventListener("click",newPracticeSong);document.querySelector("#helpButton").addEventListener("click",()=>document.querySelector("#helpDialog").showModal());document.querySelector("#statsButton").addEventListener("click",()=>{updateStats();document.querySelector("#statsDialog").showModal()});document.querySelectorAll("[data-close]").forEach(button=>button.addEventListener("click",()=>document.querySelector("#"+button.dataset.close).close()));document.querySelectorAll("dialog").forEach(dialog=>dialog.addEventListener("click",event=>{if(event.target===dialog)dialog.close()}));
  if(!songs.length){els.message.textContent="song catalog could not be loaded";els.search.disabled=true;return}setMode("daily");updateStats();
})();
