(() => {
  const songs=(window.SONGS||[]).map((song,index)=>({...song,id:index}));
  const config=window.BLAIDLE_SUPABASE||{};
  const configured=Boolean(config.url&&config.anonKey&&window.supabase?.createClient);
  const client=configured?window.supabase.createClient(config.url,config.anonKey):null;
  const $=selector=>document.querySelector(selector);
  const els={soloTab:$("#soloTab"),multiplayerTab:$("#multiplayerTab"),soloView:$("#soloView"),multiplayerView:$("#multiplayerView"),brandTagline:$("#brandTagline"),versusTab:$("#versusTab"),coopTab:$("#coopTab"),home:$("#multiplayerHome"),modeLabel:$("#multiplayerModeLabel"),title:$("#multiplayerTitle"),description:$("#multiplayerDescription"),backendNotice:$("#backendNotice"),playerName:$("#playerName"),versusOptions:$("#versusOptions"),create:$("#createRoomButton"),join:$("#joinRoomButton"),joinCode:$("#joinCode"),message:$("#multiplayerMessage"),lobby:$("#roomLobby"),roomCode:$("#roomCode"),connection:$("#connectionStatus"),copyInvite:$("#copyInviteButton"),copyCode:$("#copyCodeButton"),hostName:$("#hostName"),guestName:$("#guestName"),hostStatus:$("#hostStatus"),guestStatus:$("#guestStatus"),ready:$("#readyButton"),start:$("#startMatchButton"),leave:$("#leaveRoomButton"),lobbyMessage:$("#lobbyMessage"),game:$("#multiplayerGame"),roundLabel:$("#roundLabelMultiplayer"),matchScore:$("#matchScore"),opponentName:$("#opponentName"),opponentProgress:$("#opponentProgress"),coopLock:$("#coopLockStatus"),search:$("#multiplayerSongSearch"),suggestions:$("#multiplayerSuggestions"),guess:$("#multiplayerGuessButton"),guessStatus:$("#multiplayerGuessStatus"),gameLeave:$("#multiplayerLeaveButton"),coopDecision:$("#coopDecision"),coopChoices:$("#coopChoices"),coopDecisionStatus:$("#coopDecisionStatus"),gameMessage:$("#multiplayerGameMessage"),rows:$("#multiplayerGuessRows"),results:$("#roundResults"),resultTitle:$("#multiplayerResultTitle"),answer:$("#multiplayerAnswer"),comparison:$("#resultComparison"),resultSummary:$("#multiplayerResultSummary"),share:$("#multiplayerShareButton"),next:$("#nextRoundButton"),rematch:$("#rematchButton"),return:$("#returnMultiplayerButton")};
  const normalize=value=>String(value||"").toLowerCase().normalize("NFKD").replace(/[^a-z0-9]+/g," ").trim();
  const MAX_GUESSES=10;
  let mode="versus",matchLength=1,user=null,room=null,channel=null,selected=null,history=[],matchSummary=[],activeSuggestion=-1,autoSubmitting=false;

  function showView(view){const multiplayer=view==="multiplayer";els.soloView.hidden=multiplayer;els.multiplayerView.hidden=!multiplayer;els.soloTab.classList.toggle("active",!multiplayer);els.multiplayerTab.classList.toggle("active",multiplayer);els.soloTab.setAttribute("aria-selected",String(!multiplayer));els.multiplayerTab.setAttribute("aria-selected",String(multiplayer));els.brandTagline.textContent=multiplayer?"two players · one mystery song":"guess the drain gang song · unlimited"}
  function setMode(next,force=false){if(room&&!force)return;mode=next;const coop=mode==="coop";els.versusTab.classList.toggle("active",!coop);els.coopTab.classList.toggle("active",coop);els.versusTab.setAttribute("aria-selected",String(!coop));els.coopTab.setAttribute("aria-selected",String(coop));els.modeLabel.textContent=coop?"two player team":"1 versus 1";els.title.textContent=coop?"co-op":"versus";els.description.textContent=coop?"Lock answers separately, agree on one guess, and solve together.":"The same mystery song. Separate boards. Fewest guesses wins.";els.create.textContent=coop?"create co-op room":"create game";els.join.textContent=coop?"join co-op room":"join game";els.versusOptions.hidden=coop;els.message.textContent=""}
  function setScreen(name){els.home.hidden=name!=="home";els.lobby.hidden=name!=="lobby";els.game.hidden=name!=="game";els.results.hidden=name!=="results"}
  function setMessage(text,error=false){els.message.textContent=text;els.message.style.color=error?"var(--red-text)":""}
  function playerName(){const value=els.playerName.value.trim().slice(0,20);if(value)localStorage.setItem("blaidle-player-name",value);return value}
  async function ensureBackend(){if(!configured){els.backendNotice.hidden=false;els.backendNotice.textContent="Multiplayer needs the Supabase project values in supabase-config.js. Solo mode is still available.";throw new Error("multiplayer backend is not configured")}if(user)return user;const current=await client.auth.getSession();if(current.data.session)user=current.data.session.user;else{const signed=await client.auth.signInAnonymously();if(signed.error)throw signed.error;user=signed.data.user}return user}
  async function rpc(name,args={}){const response=await client.rpc(name,args);if(response.error)throw response.error;return response.data}
  function isHost(){return room&&user&&room.host_id===user.id}
  function ownSide(){return isHost()?"host":"guest"}
  function otherSide(){return isHost()?"guest":"host"}
  function ownName(){return isHost()?room.host_name:room.guest_name}
  function otherName(){return isHost()?room.guest_name:room.host_name}
  function songById(id){return songs[Number(id)]||null}
  function roomUrl(){const url=new URL(location.href);url.searchParams.set("multiplayer",room.mode);url.searchParams.set("room",room.code);return url.toString()}

  async function createRoom(){try{const name=playerName();if(!name)return setMessage("enter a display name",true);await ensureBackend();els.create.disabled=true;const code=await rpc("create_blaidle_room",{p_mode:mode,p_name:name,p_match_length:mode==="versus"?matchLength:1,p_catalog_size:songs.length});await enterRoom(code)}catch(error){setMessage(error.message||"could not create room",true)}finally{els.create.disabled=false}}
  async function joinRoom(){try{const name=playerName();const code=els.joinCode.value.trim().toUpperCase();if(!name)return setMessage("enter a display name",true);if(code.length!==5)return setMessage("enter a five-character room code",true);await ensureBackend();els.join.disabled=true;await rpc("join_blaidle_room",{p_code:code,p_name:name});await enterRoom(code)}catch(error){setMessage(error.message||"could not join room",true)}finally{els.join.disabled=false}}
  async function enterRoom(code){await loadRoom(code);mode=room.mode;setMode(mode,true);history=[];matchSummary=[];setScreen(room.status==="lobby"?"lobby":room.status==="playing"?"game":"results");subscribeRoom();history=await loadHistory();matchSummary=await loadMatchSummary();renderRoom();const url=new URL(location.href);url.searchParams.set("multiplayer",mode);url.searchParams.set("room",room.code);window.history.replaceState({},"",url)}
  async function loadRoom(code){const response=await client.from("blaidle_rooms").select("*").eq("code",code.toUpperCase()).single();if(response.error)throw response.error;room=response.data}
  async function loadHistory(){if(!room||room.status==="lobby")return[];try{return await rpc("get_blaidle_guess_history",{p_code:room.code})||[]}catch{return[]}}
  async function loadMatchSummary(){if(!room||room.mode!=="versus"||room.status!=="match_results")return[];try{return await rpc("get_blaidle_match_summary",{p_code:room.code})||[]}catch{return[]}}
  function subscribeRoom(){if(channel)client.removeChannel(channel);channel=client.channel(`blaidle-room-${room.code}`,{config:{presence:{key:user.id}}}).on("postgres_changes",{event:"*",schema:"public",table:"blaidle_rooms",filter:`code=eq.${room.code}`},async payload=>{if(payload.eventType==="DELETE"){room=null;history=[];matchSummary=[];setScreen("home");setMessage("The other player closed the room.");return}room=payload.new;history=await loadHistory();matchSummary=await loadMatchSummary();renderRoom()}).on("presence",{event:"sync"},()=>{const count=Object.keys(channel.presenceState()).length;els.connection.textContent=count>1?"2 connected":"1 connected";els.connection.classList.toggle("connected",count>1)}).subscribe(async status=>{if(status==="SUBSCRIBED"){await channel.track({name:ownName(),online_at:new Date().toISOString()});els.connection.textContent="connected";els.connection.classList.add("connected")}else if(status==="CHANNEL_ERROR"||status==="TIMED_OUT"){els.connection.textContent="reconnecting";els.connection.classList.remove("connected")}})}

  function renderRoom(){if(!room)return;const status=room.status;if(status==="lobby"){setScreen("lobby");renderLobby()}else if(status==="playing"){setScreen("game");renderGame()}else{setScreen("results");renderResults()}}
  function renderLobby(){els.roomCode.textContent=room.code;els.hostName.textContent=room.host_name||"waiting...";els.guestName.textContent=room.guest_name||"waiting for player";els.hostStatus.textContent=room.host_ready?"ready":"not ready";els.guestStatus.textContent=room.guest_ready?"ready":room.guest_id?"not ready":"not connected";els.hostStatus.classList.toggle("ready",room.host_ready);els.guestStatus.classList.toggle("ready",room.guest_ready);const ready=isHost()?room.host_ready:room.guest_ready;els.ready.textContent=ready?"not ready":"ready";els.start.hidden=!isHost();els.start.disabled=!(room.host_ready&&room.guest_ready);els.lobbyMessage.textContent=room.host_ready&&room.guest_ready?(isHost()?"Both players are ready. Start when you are ready.":"Both players are ready. Waiting for the host."):"The game starts after both players are ready."}
  function renderGame(){els.roundLabel.textContent=room.mode==="versus"?`round ${room.current_round} of ${room.match_length}`:"co-op round";els.matchScore.textContent=room.mode==="versus"?`${room.host_name} ${room.host_score} — ${room.guest_score} ${room.guest_name}`:`${room.host_name} + ${room.guest_name}`;const other=otherSide();const otherCount=room[`${other}_guess_count`]||0;const otherOutcome=room[`${other}_outcome`]||"playing";els.opponentName.textContent=room.mode==="versus"?(otherName()||"opponent"):"team progress";els.opponentProgress.textContent=room.mode==="versus"?`guess ${otherCount} · ${otherOutcome}`:`${room.coop_guess_count||0}/${MAX_GUESSES} guesses`;els.rows.innerHTML="";history.forEach((item,index)=>els.rows.appendChild(renderHistoryRow(item,index)));const count=room.mode==="coop"?(room.coop_guess_count||0):(room[`${ownSide()}_guess_count`]||0);els.guessStatus.textContent=`${Math.max(0,MAX_GUESSES-count)} guess${MAX_GUESSES-count===1?"":"es"} remaining`;const ownFinished=room.mode==="versus"&&room[`${ownSide()}_outcome`]!=="playing";const ownLocked=room.mode==="coop"&&room[`${ownSide()}_locked`];const deciding=room.mode==="coop"&&room.coop_proposal_host!==null&&room.coop_proposal_guest!==null;els.search.disabled=ownFinished||ownLocked||deciding;els.guess.disabled=ownFinished||ownLocked||deciding||!selected;els.coopLock.hidden=room.mode!=="coop"||!ownLocked||deciding;els.coopLock.textContent="your guess locked ✓ · waiting for teammate...";els.coopDecision.hidden=!deciding;els.gameMessage.textContent=ownFinished?`You are ${room[`${ownSide()}_outcome`]}. Waiting for your opponent...`:"";if(deciding)renderCoopDecision();else{els.coopChoices.innerHTML="";autoSubmitting=false}}
  function renderCoopDecision(){const ids=[room.coop_proposal_host,room.coop_proposal_guest];const same=ids[0]===ids[1];els.coopChoices.innerHTML="";for(const id of [...new Set(ids)]){const song=songById(id);const button=document.createElement("button");button.className="coop-choice";button.textContent=song?`${song.title} — ${song.artist}`:`song ${id}`;const ownConfirm=room[`${ownSide()}_confirm`];button.classList.toggle("selected",Number(ownConfirm)===Number(id));button.addEventListener("click",()=>confirmCoop(id));els.coopChoices.appendChild(button)}if(same){els.coopDecisionStatus.textContent="Both players chose the same song. Submitting...";if(isHost()&&!autoSubmitting){autoSubmitting=true;confirmCoop(ids[0],true)}}else{const hostVote=room.host_confirm,guestVote=room.guest_confirm;els.coopDecisionStatus.textContent=hostVote===null&&guestVote===null?"Both choices are revealed. Each player must select the same team answer.":hostVote!==null&&guestVote!==null&&hostVote!==guestVote?"You chose different answers. Choose again to agree.":"One choice is locked. Waiting for the other player."}}
  function renderHistoryRow(item,index){const song=songById(item.song_id)||{title:"unknown",artist:"",features:"",album:"",year:"",track:""};const row=document.createElement("div");row.className="guess-grid guess-row"+(item.correct?" is-correct":"");row.style.animationDelay=`${index*35}ms`;const states=item.feedback||["far","far","far","far","far","far"];row.append(makeCell(song.title,"song",stateClass(states[0])),makeCell(song.artist,"artist",stateClass(states[1])),makeCell(song.features||"none","features",stateClass(states[2])),makeCell(song.album,"album",stateClass(states[3])),makeCell(song.year,"year",stateClass(states[4]),item.year_arrow),makeCell(song.track,"track #",stateClass(states[5]),item.track_arrow));return row}
  function stateClass(state){return state==="exact"?"feedback-exact":state==="close"?"feedback-close":"feedback-far"}
  function makeCell(value,label,className="",arrow=""){const cell=document.createElement("div");cell.className=`cell ${className}`;cell.dataset.label=label;const text=document.createElement("span");text.textContent=value||"none";cell.appendChild(text);if(arrow){const a=document.createElement("span");a.className="arrow";a.textContent=arrow;cell.appendChild(a)}return cell}

  function matches(query,song){const q=normalize(query);return q&&(normalize(song.title).includes(q)||normalize(song.artist).includes(q)||normalize(song.album).includes(q))}
  function showSuggestions(){selected=null;els.guess.disabled=true;activeSuggestion=-1;const query=els.search.value;if(!normalize(query)){els.suggestions.hidden=true;return}const used=new Set(history.map(item=>Number(item.song_id)));const found=songs.filter(song=>matches(query,song)&&!used.has(song.id)).slice(0,10);els.suggestions.innerHTML="";for(const song of found){const button=document.createElement("button");button.type="button";button.className="suggestion";button.setAttribute("role","option");button.innerHTML="<strong></strong><span></span>";button.querySelector("strong").textContent=song.title;button.querySelector("span").textContent=[song.artist,song.album,song.year].filter(Boolean).join(" · ");button.addEventListener("click",()=>selectSong(song));els.suggestions.appendChild(button)}els.suggestions.hidden=!found.length}
  function selectSong(song){selected=song;els.search.value=song.title;els.suggestions.hidden=true;els.guess.disabled=false;els.guess.focus()}
  async function submitGuess(){if(!selected||!room)return;const song=selected;selected=null;els.search.value="";els.guess.disabled=true;try{if(room.mode==="versus")await rpc("submit_blaidle_versus_guess",{p_code:room.code,p_song_id:song.id});else await rpc("lock_blaidle_coop_proposal",{p_code:room.code,p_song_id:song.id});await refreshRoom()}catch(error){els.gameMessage.textContent=error.message||"guess could not be submitted"}}
  async function confirmCoop(songId,automatic=false){try{await rpc("confirm_blaidle_coop_guess",{p_code:room.code,p_song_id:Number(songId)});if(!automatic)els.coopDecisionStatus.textContent="choice locked · waiting for teammate";await refreshRoom()}catch(error){els.gameMessage.textContent=error.message||"team choice could not be submitted";autoSubmitting=false}}
  async function refreshRoom(){await loadRoom(room.code);history=await loadHistory();matchSummary=await loadMatchSummary();renderRoom()}

  function renderResults(){
    const answer=songById(room.answer_song_id);
    els.answer.textContent=answer?`${answer.title} by ${answer.artist}`:"round complete";
    els.comparison.innerHTML="";
    const matchDone=room.status==="match_results";
    if(room.mode==="versus"){
      const winner=room.round_winner;
      els.resultTitle.textContent=matchDone?(room.host_score===room.guest_score?"match tied":"match complete"):winner==="tie"?"round tied":`${winner==="host"?room.host_name:room.guest_name} wins the round`;
      for(const side of ["host","guest"]){
        const card=document.createElement("div");
        card.className="result-player"+(winner===side?" winner":"");
        const outcome=room[`${side}_outcome`];
        const guesses=room[`${side}_guess_count`];
        card.innerHTML="<strong></strong><span></span>";
        card.querySelector("strong").textContent=room[`${side}_name`];
        card.querySelector("span").textContent=outcome==="solved"?`solved in ${guesses}/${MAX_GUESSES}`:"not solved";
        els.comparison.appendChild(card);
      }
      if(matchDone&&matchSummary.length){
        const rounds=document.createElement("div");
        rounds.className="match-history";
        rounds.innerHTML=matchSummary.map(item=>`<div><strong>round ${item.round}</strong><span>${escapeHtml(room.host_name)}: ${item.host_solved?`${item.host_count}/${MAX_GUESSES}`:"failed"}</span><span>${escapeHtml(room.guest_name)}: ${item.guest_solved?`${item.guest_count}/${MAX_GUESSES}`:"failed"}</span></div>`).join("");
        els.comparison.appendChild(rounds);
      }
      els.resultSummary.textContent=`score: ${room.host_score} — ${room.guest_score}`;
      els.next.hidden=matchDone||!isHost();
      els.next.textContent="next round";
      els.rematch.hidden=!matchDone||!isHost();
    }else{
      els.resultTitle.textContent=room.coop_outcome==="solved"?"co-op solved ✓":"co-op complete";
      els.comparison.innerHTML=`<div class="result-player winner"><strong>${escapeHtml(room.host_name)} + ${escapeHtml(room.guest_name)}</strong><span>${room.coop_outcome==="solved"?`solved in ${room.coop_guess_count}/${MAX_GUESSES}`:"not solved"}</span></div>`;
      els.resultSummary.textContent="one team · one result";
      els.next.hidden=true;
      els.rematch.hidden=!isHost();
      els.rematch.textContent="play again";
    }
  }
  function escapeHtml(value){return String(value||"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]))}

  async function toggleReady(){try{const ready=room[`${ownSide()}_ready`];await rpc("set_blaidle_ready",{p_code:room.code,p_ready:!ready});await refreshRoom()}catch(error){els.lobbyMessage.textContent=error.message}}
  async function startMatch(){try{els.start.disabled=true;await rpc("start_blaidle_match",{p_code:room.code});await refreshRoom()}catch(error){els.lobbyMessage.textContent=error.message;els.start.disabled=false}}
  async function nextRound(){try{await rpc("next_blaidle_round",{p_code:room.code});history=[];await refreshRoom()}catch(error){els.resultSummary.textContent=error.message}}
  async function rematch(){try{await rpc("rematch_blaidle",{p_code:room.code});history=[];await refreshRoom()}catch(error){els.resultSummary.textContent=error.message}}
  async function leaveRoom(){const code=room?.code;try{if(configured&&code)await rpc("leave_blaidle_room",{p_code:code})}catch{}if(channel&&client)client.removeChannel(channel);channel=null;room=null;history=[];matchSummary=[];selected=null;setScreen("home");const url=new URL(location.href);url.searchParams.delete("room");url.searchParams.delete("multiplayer");window.history.replaceState({},"",url);setMode(mode)}
  async function copyText(text,button){try{await navigator.clipboard.writeText(text);const old=button.textContent;button.textContent="copied!";setTimeout(()=>button.textContent=old,1400)}catch{els.lobbyMessage.textContent="could not copy"}}
  function shareText(){if(!room)return"";const answer=songById(room.answer_song_id);if(room.mode==="coop")return`blaidle co-op\n\n${room.host_name} + ${room.guest_name}\n${room.coop_outcome==="solved"?`solved in ${room.coop_guess_count}/${MAX_GUESSES}`:"not solved"}\n\n${answer?`${answer.title} — ${answer.artist}`:""}`;return`blaidle versus\n\n${room.host_name} ${room.host_score} — ${room.guest_score} ${room.guest_name}\nround ${room.current_round}/${room.match_length}\n\n${answer?`${answer.title} — ${answer.artist}`:""}`}
  async function shareResults(){const text=shareText();try{if(navigator.share)await navigator.share({text});else await copyText(text,els.share)}catch(error){if(error?.name!=="AbortError")els.resultSummary.textContent="could not share results"}}

  els.soloTab.addEventListener("click",()=>showView("solo"));els.multiplayerTab.addEventListener("click",()=>showView("multiplayer"));els.versusTab.addEventListener("click",()=>setMode("versus"));els.coopTab.addEventListener("click",()=>setMode("coop"));document.querySelectorAll("[data-rounds]").forEach(button=>button.addEventListener("click",()=>{matchLength=Number(button.dataset.rounds);document.querySelectorAll("[data-rounds]").forEach(item=>item.classList.toggle("active",item===button))}));els.create.addEventListener("click",createRoom);els.join.addEventListener("click",joinRoom);els.joinCode.addEventListener("input",()=>els.joinCode.value=els.joinCode.value.toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,5));els.copyInvite.addEventListener("click",()=>copyText(roomUrl(),els.copyInvite));els.copyCode.addEventListener("click",()=>copyText(room.code,els.copyCode));els.ready.addEventListener("click",toggleReady);els.start.addEventListener("click",startMatch);els.leave.addEventListener("click",leaveRoom);els.gameLeave.addEventListener("click",leaveRoom);els.next.addEventListener("click",nextRound);els.rematch.addEventListener("click",rematch);els.return.addEventListener("click",leaveRoom);els.share.addEventListener("click",shareResults);els.search.addEventListener("input",showSuggestions);els.search.addEventListener("keydown",event=>{const items=[...els.suggestions.querySelectorAll(".suggestion")];if(event.key==="ArrowDown"||event.key==="ArrowUp"){event.preventDefault();if(items.length){activeSuggestion=(activeSuggestion+(event.key==="ArrowDown"?1:-1)+items.length)%items.length;items.forEach((item,index)=>item.classList.toggle("active",index===activeSuggestion));items[activeSuggestion].scrollIntoView({block:"nearest"})}}else if(event.key==="Enter"){event.preventDefault();if(!els.suggestions.hidden&&activeSuggestion>=0)items[activeSuggestion].click();else if(selected)submitGuess()}else if(event.key==="Escape")els.suggestions.hidden=true});els.guess.addEventListener("click",submitGuess);document.addEventListener("click",event=>{if(!event.target.closest("#multiplayerSearchWrap"))els.suggestions.hidden=true});

  els.playerName.value=localStorage.getItem("blaidle-player-name")||"";if(!configured){els.backendNotice.hidden=false;els.backendNotice.textContent="Multiplayer is installed but needs Supabase configuration before rooms can be created.";els.create.disabled=true;els.join.disabled=true}const params=new URLSearchParams(location.search);if(params.get("multiplayer")){showView("multiplayer");setMode(params.get("multiplayer")==="coop"?"coop":"versus");if(params.get("room")){els.joinCode.value=params.get("room").toUpperCase();setMessage("Enter your name, then join the invited room.")}}else setMode("versus");
})();
